version: 1
builder:
  configs:
  - platform: ios
    scheme: TinkoffConcurrency
  - platform: macos-xcodebuild
    scheme: TinkoffConcurrency
  - platform: tvos
    scheme: TinkoffConcurrency
  - platform: watchos
    scheme: TinkoffConcurrency
  - documentation_targets: [TinkoffConcurrency]
