name: publish
 
on:
  workflow_dispatch:
    inputs:
      bump_type:
        default: "patch"
        required: true
        type: string
 
jobs:
  publish:
    uses: tinkoff-mobile-tech/workflows/.github/workflows/ios_lib.publish.yml@v1
    with:
      bump_type: ${{ github.event.inputs.bump_type }}
    secrets:
      cocapods_trunk_token: ${{ secrets.COCOAPODS_TRUNK_TOKEN }}